# Generated by Django 6.0.4 on 2026-05-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='price',
            field=models.IntegerField(default=5000),
        ),
        migrations.AddField(
            model_name='flight',
            name='seat_number',
            field=models.CharField(default='A1', max_length=10),
        ),
    ]
