# Generated by Django 6.0.4 on 2026-05-04 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_flight_price_flight_seat_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='seat_number',
        ),
        migrations.AddField(
            model_name='booking',
            name='seat_number',
            field=models.CharField(default='A1', max_length=10),
            preserve_default=False,
        ),
    ]
